import { useState } from 'react';
import PartEditor from './PartEditor';
import { authHeaders } from './apiAuth';

/**
 * ReadingTestWizard
 * ------------------
 * Step-by-step form for building (or editing) an IELTS Reading test —
 * the counterpart to SpeakingTestWizard.jsx / WritingTestWizard.jsx, using
 * the same create/edit dual-mode shape (initialTest present → PATCH,
 * absent → POST) and the same scroll-safe layout (scrollable content,
 * fixed header/footer bars, never `sticky`).
 *
 * Unlike Speaking/Writing, Reading's internal state IS the backend shape
 * directly — `parts` is exactly `Test.parts` (title/passageText/
 * questionGroups per passage) — so passage/question editing reuses the
 * same PartEditor + QuestionGroupEditor components TestDraftEditor.jsx
 * already uses for PDF-uploaded Reading tests. No translation layer is
 * needed there.
 *
 * The one thing that DOES need translating is the "Import via JSON"
 * feature: teachers can paste JSON generated by an AI assistant (ChatGPT,
 * Claude, etc. — see MASTER_AI_PROMPT below) using a friendlier authoring
 * shape (paragraphs with letter labels, a shared headings pool + mappings
 * for matching-heading questions) that doesn't match the backend schema
 * 1:1. `parseReadingImportJson` validates that shape, and
 * `mapImportJsonToParts` converts a valid result into real `parts`.
 *
 * Listening still uses the older PDF-upload → TestDraftEditor flow
 * (TestBuilder.jsx) — this wizard is Reading-only for now.
 */

const STEPS = ['Test Details', 'Passages & Questions', 'Review & Save'];
const MAX_PASSAGES = 5;

// The question types the JSON import understands, and how each maps onto
// the backend's existing questionSchema.type enum (backend/models/Test.js)
// for grading purposes. note_completion/table_completion blanks are still
// graded as plain fill-in-the-blank — what's different for them is the
// GROUP's own questionType label (see IMPORT_TYPE_TO_GROUP_LABEL below),
// which tells TestInterface.jsx to render the original note/table layout
// instead of one isolated line per question.
const IMPORT_TYPE_TO_BACKEND_TYPE = {
  multiple_choice: 'multiple-choice',
  matching_headings: 'matching-heading',
  // Sentence/summary matching, e.g. "Match each sentence beginning (16-20)
  // to the correct ending (A-F)" — same shared-pool shape as matching
  // headings, graded as matching-information (see mapImportJsonToParts).
  sentence_matching: 'matching-information',
  fill_in_blanks: 'fill-in-the-blank',
  note_completion: 'fill-in-the-blank',
  table_completion: 'fill-in-the-blank',
  // Map/plan labeling with a radio grid, e.g. "Label the plan below. Choose
  // the correct letter, A-H." — its own backend type (matrix-matching),
  // rendered by TestInterface.jsx's MatrixMatchingGroup as an image beside a
  // question-rows × option-columns table of radio buttons, NOT the
  // drag-and-drop word bank (see mapImageUrl/matrixOptions below).
  matrix_matching: 'matrix-matching',
};
const VALID_IMPORT_TYPES = Object.keys(IMPORT_TYPE_TO_BACKEND_TYPE);
// Import types whose questions are answered via a shared drag-and-drop word
// bank (TestInterface.jsx's WordBankDropSlot) rather than free text or their
// own separate per-question options — see backend/models/Test.js's
// questionGroupSchema.wordBank.
const SHARED_POOL_IMPORT_TYPES = ['matching_headings', 'sentence_matching'];

// Only note_completion/table_completion need a group-level label distinct
// from their (shared, fill-in-the-blank) question type — everything else
// falls back to IMPORT_TYPE_TO_BACKEND_TYPE's mapping, which already
// matches 1:1 at the group level.
const IMPORT_TYPE_TO_GROUP_LABEL = {
  note_completion: 'note-completion',
  table_completion: 'table-completion',
};

// Shown inside the Import modal so teachers know exactly what to paste
// into an AI assistant to get compatible JSON back.
const MASTER_AI_PROMPT = `You are generating IELTS Academic Reading test content as JSON for an online test platform. Using the passage(s) I provide (or realistic IELTS-style academic passages if I don't provide one), output ONLY valid JSON — no markdown code fences, no commentary — matching exactly this structure:

{
  "title": "string, e.g. 'Cambridge 21 Test 4 — Academic Reading'",
  "durationMinutes": 60,
  "passages": [
    {
      "passageNumber": 1,
      "title": "string",
      "paragraphs": [
        { "label": "A", "text": "full paragraph text" },
        { "label": "B", "text": "full paragraph text" }
      ],
      "questionGroups": [
        {
          "groupInstructions": "e.g. 'Questions 1-5: Choose the correct letter, A, B, C or D.'",
          "questionType": "multiple_choice",
          "startNumber": 1,
          "endNumber": 5,
          "questions": [
            {
              "questionNumber": 1,
              "prompt": "question text",
              "options": ["option A text", "option B text", "option C text", "option D text"],
              "correctAnswer": "must exactly match one of the options",
              "answer": "the answer key text shown to teachers, e.g. 'B' or the matching option text",
              "explanation": "1-3 sentences explaining why this answer is correct, referencing the passage"
            }
          ]
        },
        {
          "groupInstructions": "e.g. 'Questions 6-10: Match each paragraph with the correct heading.'",
          "questionType": "matching_headings",
          "startNumber": 6,
          "endNumber": 10,
          "headingsPool": ["Heading i", "Heading ii", "Heading iii", "Heading iv"],
          "mappings": [
            {
              "paragraph": "A",
              "questionNumber": 6,
              "correctHeading": "must exactly match one entry in headingsPool",
              "answer": "the answer key text shown to teachers, e.g. the correct heading",
              "explanation": "1-3 sentences explaining why this heading matches the paragraph"
            }
          ]
        },
        {
          "groupInstructions": "e.g. 'Questions 11-14: Complete the summary below using the words in the box. Choose the correct letter, A-F.'",
          "questionType": "fill_in_blanks",
          "startNumber": 11,
          "endNumber": 14,
          "wordLimit": "NO MORE THAN TWO WORDS",
          "wordBank": ["OPTIONAL: e.g. 'funding', 'trees', 'moral standards' — a shared list of words/phrases students drag into the blanks instead of typing. Omit entirely for a normal typed fill-in-the-blank."],
          "allowRepeatWordBankOptions": false,
          "questions": [
            {
              "questionNumber": 11,
              "prompt": "sentence with a ___ blank",
              "correctAnswer": "the missing word(s) — if wordBank is set, this MUST exactly match one entry in wordBank",
              "answer": "the answer key text shown to teachers",
              "explanation": "1-3 sentences explaining why this is the correct word(s), referencing the passage"
            }
          ]
        },
        {
          "groupInstructions": "e.g. 'Questions 15-18: Complete the notes below. Write NO MORE THAN TWO WORDS for each answer.'",
          "questionType": "note_completion",
          "startNumber": 15,
          "endNumber": 18,
          "wordLimit": "NO MORE THAN TWO WORDS",
          "wordBank": [],
          "allowRepeatWordBankOptions": false,
          "layoutLines": [
            "# Company History",
            "- Founded in [[15]] by two engineers",
            "- Grew rapidly after receiving [[16]] in funding",
            "- Now employs over [[17]] people across [[18]] offices"
          ],
          "questions": [
            { "questionNumber": 15, "prompt": "Founding year", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." },
            { "questionNumber": 16, "prompt": "Amount of funding received", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." },
            { "questionNumber": 17, "prompt": "Number of employees", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." },
            { "questionNumber": 18, "prompt": "Number of offices", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." }
          ]
        },
        {
          "groupInstructions": "e.g. 'Questions 19-22: Complete the table below. Write NO MORE THAN THREE WORDS for each answer.'",
          "questionType": "table_completion",
          "startNumber": 19,
          "endNumber": 22,
          "wordLimit": "NO MORE THAN THREE WORDS",
          "wordBank": [],
          "allowRepeatWordBankOptions": false,
          "tableColumns": ["Year", "Revenue", "Notes"],
          "tableRows": [
            ["2020", "[[19]]", "Pandemic slowdown"],
            ["2021", "[[20]]", "[[21]] growth"],
            ["2022", "[[22]]", "Record year"]
          ],
          "questions": [
            { "questionNumber": 19, "prompt": "Revenue in 2020", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." },
            { "questionNumber": 20, "prompt": "Revenue in 2021", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." },
            { "questionNumber": 21, "prompt": "Type of growth in 2021", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." },
            { "questionNumber": 22, "prompt": "Revenue in 2022", "correctAnswer": "the missing word(s)", "answer": "...", "explanation": "..." }
          ]
        },
        {
          "groupInstructions": "e.g. 'Questions 23-26: Complete each sentence with the correct ending, A-F, below.'",
          "questionType": "sentence_matching",
          "startNumber": 23,
          "endNumber": 26,
          "wordBank": ["A sentence-ending fragment, e.g. 'because funding had run out.'", "another ending fragment", "..."],
          "allowRepeatWordBankOptions": false,
          "mappings": [
            {
              "questionNumber": 23,
              "promptText": "the sentence BEGINNING the student is matching an ending to, e.g. 'The project was delayed'",
              "correctFragment": "must exactly match one entry in wordBank",
              "answer": "the answer key text shown to teachers, e.g. the correct ending",
              "explanation": "1-3 sentences explaining why this ending matches, referencing the passage"
            }
          ]
        },
        {
          "groupInstructions": "e.g. 'Questions 27-30: Label the plan below. Choose the correct letter, A-H.'",
          "questionType": "matrix_matching",
          "startNumber": 27,
          "endNumber": 30,
          "mapImageUrl": "OPTIONAL: a data URL or hosted URL for the map/plan/diagram image being labeled — omit or leave '' if no image is available; the source material should describe one even if you can't embed the actual pixels",
          "matrixOptions": ["A", "B", "C", "D", "E", "F", "G", "H"],
          "questions": [
            {
              "questionNumber": 27,
              "prompt": "short label for this row, e.g. 'Reception desk'",
              "correctAnswer": "must exactly match one entry in matrixOptions, e.g. 'C'",
              "answer": "the answer key text shown to teachers",
              "explanation": "1-3 sentences explaining why this location/letter is correct, referencing the passage"
            }
          ]
        }
      ]
    }
  ]
}

Rules:
- "questionType" must be exactly one of: multiple_choice, matching_headings, sentence_matching, fill_in_blanks, note_completion, table_completion, matrix_matching.
- Every questionNumber across the whole test must be unique and sequential, starting at 1.
- For matching_headings, each mapping's correctHeading must exactly match one entry in headingsPool — students drag each heading from a word bank onto its paragraph's question number, they don't type anything.
- For sentence_matching (sentence/summary-ending matching, e.g. "choose the correct ending, A-F"), "wordBank" is the shared pool of ending fragments/options and each mapping's correctFragment must exactly match one entry in it — same drag-and-drop word-bank interaction as matching_headings, just for sentence endings instead of paragraph headings.
- For matrix_matching (map/plan/diagram labeling, e.g. "Label the plan below, choose the correct letter A-H" — common in both Listening and, occasionally, Reading diagram-labeling tasks), "matrixOptions" is the shared list of column letters/labels and every question's correctAnswer must exactly match one entry in it. Unlike matching_headings/sentence_matching, this is answered with a grid of radio buttons (one option per row, NOT drag-and-drop), so the SAME option letter may correctly be reused across more than one row — do not treat matrixOptions as a pool that shrinks. "mapImageUrl" is optional (omit/leave blank if you have no real image to provide); still write "prompt" for each question as if there IS a diagram being labeled, describing the location in words (e.g. "Reception desk").
- For multiple_choice, correctAnswer must exactly match one of that question's options.
- For fill_in_blanks, note_completion, and table_completion, "wordBank" is OPTIONAL: include it (a non-empty array of words/phrases, Cambridge-style "choose from the box, A-J") ONLY when the source material provides a fixed set of options students pick from rather than typing freely — a classic "summary completion with a box" task. Omit it (or leave it an empty array) for an ordinary typed-answer blank. When wordBank is set, every affected question's correctAnswer must exactly match one entry in wordBank, and "allowRepeatWordBankOptions" (default false) controls whether the same option may be used more than once.
- For note_completion, "layoutLines" is the note/summary text EXACTLY as it should be shown to the student, one array entry per line: a line starting with "# " renders as a bold sub-heading, a line starting with "- " renders as a bullet point, anything else is a plain paragraph line. Mark every blank inline, in place, as "[[n]]" (double brackets) where n is that blank's questionNumber — e.g. "- Founded in [[15]] by two engineers". Every questionNumber in the group's range must appear as a "[[n]]" marker somewhere in layoutLines.
- For table_completion, "tableColumns" are the column headers left-to-right, and "tableRows" is the table body — each row is an array of cell strings in the same column order. Mark every blank cell as "[[n]]" (double brackets), same as note_completion. Every questionNumber in the group's range must appear as a "[[n]]" marker somewhere in tableRows.
- The "[[n]]" marker format is strict and must be followed EXACTLY, because the student-facing renderer parses it with a literal regex, not a fuzzy match: double square brackets directly around digits only — "[[15]]" — with NO space anywhere inside the brackets ("[[ 15 ]]" or "[[15 ]]" will NOT be recognized and that blank will silently fail to render as an input), no letters or punctuation inside the brackets, and no single-bracket "[15]" style. This applies identically inside both "layoutLines" strings and "tableRows" cell strings. Each marker is replaced in place by an interactive numbered input box, so the surrounding words in the sentence/cell must read naturally with the marker removed and a blank left in its exact spot (e.g. "Founded in [[15]] by two engineers" reads correctly once [[15]] becomes an input box).
- For note_completion and table_completion, still include the normal flat "questions" array (one entry per blank, in questionNumber order) exactly like fill_in_blanks — this is what stores the answer key/explanation and grades the response; "prompt" there can be a short label for that blank (e.g. "Founding year") since the real question text is the surrounding note/table, not this field.
- Every question (and every matching_headings/sentence_matching mapping) must include "answer" and "explanation" strings — "answer" is the teacher-facing answer key text, and "explanation" briefly justifies it by referencing the passage. These are shown only to teachers reviewing the test, never to students.
- Include 2–3 passages for a full test, each with its own paragraphs and questionGroups.
- Output raw JSON only.`;

function emptyPart(partNumber) {
  return {
    partNumber,
    title: '',
    instructions: 'Read the text and answer the questions.',
    passageText: '',
    questionGroups: [],
  };
}

function resizePartsCount(parts, size) {
  const n = Math.max(1, Math.min(MAX_PASSAGES, Number(size) || 0));
  if (n === parts.length) return parts;
  if (n < parts.length) return parts.slice(0, n);
  const additions = Array.from({ length: n - parts.length }, (_, i) => emptyPart(parts.length + i + 1));
  return [...parts, ...additions];
}

function countQuestions(parts) {
  return (parts || []).reduce(
    (sum, p) => sum + (p.questionGroups || []).reduce((s, g) => s + (g.questions || []).length, 0),
    0
  );
}

/**
 * Validates a parsed (already JSON.parse'd) import object against the
 * shape MASTER_AI_PROMPT asks the AI to produce. Returns every problem
 * found (not just the first) so a teacher can fix a bad paste in one pass
 * instead of hitting errors one at a time.
 */
function validateReadingImportJson(parsed) {
  const errors = [];

  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return { valid: false, errors: ['The pasted JSON must be an object, e.g. { "title": ..., "passages": [...] }.'] };
  }

  if (typeof parsed.title !== 'string' || !parsed.title.trim()) {
    errors.push('Missing or empty "title" string.');
  }

  if (!Array.isArray(parsed.passages) || parsed.passages.length === 0) {
    errors.push('Missing "passages" array (must contain at least one passage).');
    return { valid: false, errors }; // nothing else meaningful to check without passages
  }

  parsed.passages.forEach((passage, pi) => {
    const pLabel = `Passage ${pi + 1}`;

    if (!passage || typeof passage !== 'object') {
      errors.push(`${pLabel}: must be an object.`);
      return;
    }

    if (!Array.isArray(passage.paragraphs) || passage.paragraphs.length === 0) {
      errors.push(`${pLabel}: missing "paragraphs" array.`);
    } else {
      passage.paragraphs.forEach((para, li) => {
        if (!para || typeof para.label !== 'string' || !para.label.trim()) {
          errors.push(`${pLabel}, paragraph ${li + 1}: missing "label".`);
        }
        if (!para || typeof para.text !== 'string' || !para.text.trim()) {
          errors.push(`${pLabel}, paragraph ${li + 1}: missing "text".`);
        }
      });
    }

    if (!Array.isArray(passage.questionGroups) || passage.questionGroups.length === 0) {
      errors.push(`${pLabel}: missing "questionGroups" array.`);
      return;
    }

    passage.questionGroups.forEach((group, gi) => {
      const gLabel = `${pLabel}, question group ${gi + 1}`;

      if (!group || typeof group !== 'object') {
        errors.push(`${gLabel}: must be an object.`);
        return;
      }
      if (!VALID_IMPORT_TYPES.includes(group.questionType)) {
        errors.push(`${gLabel}: invalid question type "${group.questionType}". Expected one of ${VALID_IMPORT_TYPES.join(', ')}.`);
      }
      if (!group.groupInstructions || typeof group.groupInstructions !== 'string') {
        errors.push(`${gLabel}: missing "groupInstructions".`);
      }
      if (typeof group.startNumber !== 'number' || typeof group.endNumber !== 'number') {
        errors.push(`${gLabel}: missing or invalid "startNumber"/"endNumber" (must be numbers).`);
      }

      // Optional shared word-bank fields any group may carry (see
      // backend/models/Test.js's questionGroupSchema.wordBank) — validated
      // once here so both the shared-pool types (matching_headings/
      // sentence_matching, which always have one) and the optional-word-bank
      // types below (fill_in_blanks/note_completion/table_completion) get
      // the same shape check.
      function checkWordBankField(pool, label) {
        if (pool == null) return;
        if (!Array.isArray(pool) || pool.some((o) => typeof o !== 'string' || !o.trim())) {
          errors.push(`${label}: "wordBank" must be an array of non-empty strings.`);
        }
        if (group.allowRepeatWordBankOptions != null && typeof group.allowRepeatWordBankOptions !== 'boolean') {
          errors.push(`${label}: "allowRepeatWordBankOptions" must be a boolean.`);
        }
      }

      if (group.questionType === 'matching_headings' || group.questionType === 'sentence_matching') {
        const isHeadings = group.questionType === 'matching_headings';
        const poolField = isHeadings ? 'headingsPool' : 'wordBank';
        const pool = isHeadings ? group.headingsPool : group.wordBank;
        if (!Array.isArray(pool) || pool.length === 0) {
          errors.push(`${gLabel}: missing "${poolField}" array.`);
        }
        if (!isHeadings) checkWordBankField(group.wordBank, gLabel);
        if (!Array.isArray(group.mappings) || group.mappings.length === 0) {
          errors.push(`${gLabel}: missing "mappings" array.`);
        } else {
          group.mappings.forEach((m, mi) => {
            const mLabel = `${gLabel}, mapping ${mi + 1}`;
            if (!m || typeof m.questionNumber !== 'number') errors.push(`${mLabel}: missing/invalid "questionNumber".`);
            if (isHeadings) {
              if (!m || !m.paragraph) errors.push(`${mLabel}: missing "paragraph".`);
              if (!m || !m.correctHeading) errors.push(`${mLabel}: missing "correctHeading".`);
              if (m && Array.isArray(pool) && m.correctHeading && !pool.includes(m.correctHeading)) {
                errors.push(`${mLabel}: "correctHeading" must exactly match one entry in headingsPool.`);
              }
            } else {
              if (!m || typeof m.promptText !== 'string' || !m.promptText.trim()) errors.push(`${mLabel}: missing "promptText".`);
              if (!m || !m.correctFragment) errors.push(`${mLabel}: missing "correctFragment".`);
              if (m && Array.isArray(pool) && m.correctFragment && !pool.includes(m.correctFragment)) {
                errors.push(`${mLabel}: "correctFragment" must exactly match one entry in wordBank.`);
              }
            }
            // "answer"/"explanation" are optional (older imports may omit them) but
            // must be strings when present, so a stray object/number doesn't
            // silently get saved into the teacher answer key.
            if (m && m.answer != null && typeof m.answer !== 'string') errors.push(`${mLabel}: "answer" must be a string.`);
            if (m && m.explanation != null && typeof m.explanation !== 'string') errors.push(`${mLabel}: "explanation" must be a string.`);
          });
        }
      } else if (
        group.questionType === 'multiple_choice' ||
        group.questionType === 'fill_in_blanks' ||
        group.questionType === 'note_completion' ||
        group.questionType === 'table_completion'
      ) {
        const hasWordBank = group.questionType !== 'multiple_choice' && Array.isArray(group.wordBank) && group.wordBank.length > 0;
        if (group.questionType !== 'multiple_choice') checkWordBankField(group.wordBank, gLabel);

        if (!Array.isArray(group.questions) || group.questions.length === 0) {
          errors.push(`${gLabel}: missing "questions" array.`);
        } else {
          group.questions.forEach((q, qi) => {
            const qLabel = `${gLabel}, question ${qi + 1}`;
            if (!q || typeof q.questionNumber !== 'number') errors.push(`${qLabel}: missing/invalid "questionNumber".`);
            if (!q || typeof q.prompt !== 'string' || !q.prompt.trim()) errors.push(`${qLabel}: missing "prompt".`);
            if (!q || q.correctAnswer == null || q.correctAnswer === '') errors.push(`${qLabel}: missing "correctAnswer".`);
            if (group.questionType === 'multiple_choice' && (!Array.isArray(q.options) || q.options.length < 2)) {
              errors.push(`${qLabel}: multiple_choice questions need an "options" array with at least 2 choices.`);
            }
            if (hasWordBank && q && typeof q.correctAnswer === 'string' && !group.wordBank.includes(q.correctAnswer)) {
              errors.push(`${qLabel}: "correctAnswer" must exactly match one entry in the group's "wordBank".`);
            }
            // "answer"/"explanation" are optional (older imports may omit them) but
            // must be strings when present.
            if (q && q.answer != null && typeof q.answer !== 'string') errors.push(`${qLabel}: "answer" must be a string.`);
            if (q && q.explanation != null && typeof q.explanation !== 'string') errors.push(`${qLabel}: "explanation" must be a string.`);
          });
        }

        if (group.questionType === 'note_completion') {
          if (!Array.isArray(group.layoutLines) || group.layoutLines.length === 0) {
            errors.push(`${gLabel}: note_completion needs a non-empty "layoutLines" array.`);
          } else {
            if (group.layoutLines.some((l) => typeof l !== 'string')) {
              errors.push(`${gLabel}: every "layoutLines" entry must be a string.`);
            }
            checkBlankMarkersCoverGroup(group, group.layoutLines.join('\n'), gLabel, errors);
          }
        }

        if (group.questionType === 'table_completion') {
          if (!Array.isArray(group.tableColumns) || group.tableColumns.length === 0) {
            errors.push(`${gLabel}: table_completion needs a non-empty "tableColumns" array.`);
          }
          if (!Array.isArray(group.tableRows) || group.tableRows.length === 0) {
            errors.push(`${gLabel}: table_completion needs a non-empty "tableRows" array.`);
          } else {
            group.tableRows.forEach((row, ri) => {
              if (!Array.isArray(row)) errors.push(`${gLabel}, table row ${ri + 1}: must be an array of cell strings.`);
            });
            const flatCells = group.tableRows
              .filter(Array.isArray)
              .flat()
              .map((c) => String(c ?? ''))
              .join('\n');
            checkBlankMarkersCoverGroup(group, flatCells, gLabel, errors);
          }
        }
      } else if (group.questionType === 'matrix_matching') {
        // Map/plan labeling radio grid — see mapImportJsonToParts and
        // backend/models/Test.js's questionGroupSchema.mapImageUrl/matrixOptions.
        // Not a SHARED_POOL_IMPORT_TYPES/mappings type: it uses the same flat
        // "questions" array shape as fill_in_blanks (one entry per row), just
        // with its own group-level image + option-column fields instead of a
        // wordBank.
        if (group.mapImageUrl != null && typeof group.mapImageUrl !== 'string') {
          errors.push(`${gLabel}: "mapImageUrl" must be a string when present.`);
        }
        if (!Array.isArray(group.matrixOptions) || group.matrixOptions.length === 0) {
          errors.push(`${gLabel}: missing "matrixOptions" array (the column letters/labels, e.g. ["A","B","C","D"]).`);
        } else if (group.matrixOptions.some((o) => typeof o !== 'string' || !o.trim())) {
          errors.push(`${gLabel}: every "matrixOptions" entry must be a non-empty string.`);
        }
        if (!Array.isArray(group.questions) || group.questions.length === 0) {
          errors.push(`${gLabel}: missing "questions" array.`);
        } else {
          group.questions.forEach((q, qi) => {
            const qLabel = `${gLabel}, question ${qi + 1}`;
            if (!q || typeof q.questionNumber !== 'number') errors.push(`${qLabel}: missing/invalid "questionNumber".`);
            if (!q || typeof q.prompt !== 'string' || !q.prompt.trim()) errors.push(`${qLabel}: missing "prompt".`);
            if (!q || q.correctAnswer == null || q.correctAnswer === '') errors.push(`${qLabel}: missing "correctAnswer".`);
            if (
              q &&
              Array.isArray(group.matrixOptions) &&
              typeof q.correctAnswer === 'string' &&
              !group.matrixOptions.includes(q.correctAnswer)
            ) {
              errors.push(`${qLabel}: "correctAnswer" must exactly match one entry in the group's "matrixOptions".`);
            }
            if (q && q.answer != null && typeof q.answer !== 'string') errors.push(`${qLabel}: "answer" must be a string.`);
            if (q && q.explanation != null && typeof q.explanation !== 'string') errors.push(`${qLabel}: "explanation" must be a string.`);
          });
        }
      }
      // questionType itself already flagged above if invalid — no questions/mappings to check further
    });
  });

  return { valid: errors.length === 0, errors };
}

/**
 * Cross-checks that every questionNumber in a note_completion/
 * table_completion group's range actually appears as a "[[n]]" marker
 * somewhere in the group's layout text/table cells — catches the AI
 * forgetting to place a blank, which would otherwise silently drop that
 * question from the student-facing render (no input box would ever appear
 * for it) despite it still existing in the answer key.
 */
function checkBlankMarkersCoverGroup(group, combinedText, gLabel, errors) {
  if (typeof group.startNumber !== 'number' || typeof group.endNumber !== 'number') return;
  const markers = new Set(Array.from(combinedText.matchAll(/\[\[(\d+)\]\]/g), (m) => Number(m[1])));
  for (let n = group.startNumber; n <= group.endNumber; n++) {
    if (!markers.has(n)) {
      errors.push(`${gLabel}: no "[[${n}]]" blank marker found for question ${n} in its layout/table.`);
    }
  }
}

/** Converts a validated import object into a real `parts` array. */
function mapImportJsonToParts(parsed) {
  return parsed.passages.map((passage, pi) => {
    const passageText = (passage.paragraphs || [])
      .map((p) => `${p.label}\n\n${p.text}`)
      .join('\n\n');

    const questionGroups = (passage.questionGroups || []).map((group) => {
      const backendType = IMPORT_TYPE_TO_BACKEND_TYPE[group.questionType];

      if (SHARED_POOL_IMPORT_TYPES.includes(group.questionType)) {
        const isHeadings = group.questionType === 'matching_headings';
        // Both matching_headings and sentence_matching are answered by
        // dragging one shared option (a heading or a sentence-ending
        // fragment) into a slot — see backend/models/Test.js's
        // questionGroupSchema.wordBank and TestInterface.jsx's
        // WordBankDropSlot. headingsPool is matching_headings' own name for
        // its pool; sentence_matching already calls it wordBank.
        const pool = isHeadings ? group.headingsPool : group.wordBank;
        const questions = group.mappings.map((m) => ({
          questionNumber: m.questionNumber,
          type: backendType,
          prompt: isHeadings ? `Paragraph ${m.paragraph}` : m.promptText,
          options: pool,
          correctAnswer: isHeadings ? m.correctHeading : m.correctFragment,
          answer: m.answer || '',
          explanation: m.explanation || '',
        }));
        return {
          groupInstructions: group.groupInstructions,
          questionType: backendType,
          startNumber: group.startNumber,
          endNumber: group.endNumber,
          // Populating wordBank here is what turns on the drag-and-drop UI
          // for these question types (previously matching-heading questions
          // had no answering UI at all — headingsPool/dropSlotNumber were
          // never wired into any rendering path).
          wordBank: pool || [],
          allowRepeatWordBankOptions: Boolean(group.allowRepeatWordBankOptions),
          questions,
        };
      }

      if (group.questionType === 'matrix_matching') {
        // Map/plan labeling radio grid — TestInterface.jsx's
        // MatrixMatchingGroup, not the drag-and-drop word bank: each
        // question picks ONE option per row via a radio button, so
        // mapImageUrl/matrixOptions are their own group-level fields
        // (backend/models/Test.js) rather than reusing wordBank.
        const questions = group.questions.map((q) => ({
          questionNumber: q.questionNumber,
          type: backendType,
          prompt: q.prompt,
          options: group.matrixOptions || [],
          correctAnswer: q.correctAnswer,
          answer: q.answer || '',
          explanation: q.explanation || '',
        }));
        return {
          groupInstructions: group.groupInstructions,
          questionType: backendType,
          startNumber: group.startNumber,
          endNumber: group.endNumber,
          mapImageUrl: group.mapImageUrl || '',
          matrixOptions: group.matrixOptions || [],
          questions,
        };
      }

      const questions = group.questions.map((q) => ({
        questionNumber: q.questionNumber,
        type: backendType,
        prompt: q.prompt,
        options: group.questionType === 'multiple_choice' ? q.options : [],
        correctAnswer: q.correctAnswer,
        wordLimit: group.wordLimit || q.wordLimit || null,
        answer: q.answer || '',
        explanation: q.explanation || '',
      }));
      const hasWordBank = group.questionType !== 'multiple_choice' && Array.isArray(group.wordBank) && group.wordBank.length > 0;
      return {
        groupInstructions: group.groupInstructions,
        // note_completion/table_completion get their own layout-only group
        // label (IMPORT_TYPE_TO_GROUP_LABEL) so TestInterface.jsx renders
        // the structured layout below instead of one line per question;
        // every other type's group label matches its (shared) backend type.
        questionType: IMPORT_TYPE_TO_GROUP_LABEL[group.questionType] || backendType,
        startNumber: group.startNumber,
        endNumber: group.endNumber,
        ...(group.questionType === 'note_completion' ? { layoutText: (group.layoutLines || []).join('\n') } : {}),
        ...(group.questionType === 'table_completion'
          ? { tableColumns: group.tableColumns || [], tableRows: group.tableRows || [] }
          : {}),
        // Optional shared word bank — Cambridge-style "choose from the box"
        // completion. Only set when the teacher's JSON actually included
        // one; an ordinary typed blank carries no wordBank at all.
        ...(hasWordBank ? { wordBank: group.wordBank, allowRepeatWordBankOptions: Boolean(group.allowRepeatWordBankOptions) } : {}),
        questions,
      };
    });

    return {
      partNumber: passage.passageNumber || pi + 1,
      title: passage.title || `Passage ${pi + 1}`,
      instructions: passage.instructions || 'Read the text and answer the questions.',
      passageText,
      questionGroups,
    };
  });
}

/* -------------------------------------------------------------------------
 * Import via JSON — modal with the paste box, validation errors, and the
 * Master AI Prompt teachers copy into ChatGPT/Claude to get compatible
 * JSON back. Scrolls internally (own flex-1/overflow-y-auto region) so a
 * long error list or the prompt text never gets clipped by the viewport.
 * ---------------------------------------------------------------------- */
function ImportJsonModal({ onClose, onImport }) {
  const [jsonText, setJsonText] = useState('');
  const [errors, setErrors] = useState([]);
  const [copied, setCopied] = useState(false);

  function handleParse() {
    let parsed;
    try {
      parsed = JSON.parse(jsonText);
    } catch (err) {
      setErrors([`Invalid JSON: ${err.message}`]);
      return;
    }

    const result = validateReadingImportJson(parsed);
    if (!result.valid) {
      setErrors(result.errors);
      return;
    }

    setErrors([]);
    onImport(parsed);
  }

  async function handleCopyPrompt() {
    try {
      await navigator.clipboard.writeText(MASTER_AI_PROMPT);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API unavailable (e.g. insecure context) — the prompt is
      // still fully visible and selectable below, so this is a soft no-op.
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4 py-8">
      <div className="flex max-h-full w-full max-w-2xl flex-col rounded-2xl bg-white shadow-xl">
        <div className="flex shrink-0 items-center justify-between border-b border-neutral-200 px-6 py-4">
          <h2 className="text-base font-bold text-neutral-900">Import via JSON</h2>
          <button
            onClick={onClose}
            className="flex h-7 w-7 items-center justify-center rounded-lg text-neutral-400 transition hover:bg-neutral-100 hover:text-neutral-600"
          >
            ✕
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-6 py-4">
          <p className="mb-3 text-sm text-neutral-600">
            Paste JSON generated by an AI assistant (see the Master AI Prompt below) to auto-populate this test's
            title, passages, and questions.
          </p>

          <textarea
            value={jsonText}
            onChange={(e) => setJsonText(e.target.value)}
            rows={10}
            placeholder='{ "title": "...", "durationMinutes": 60, "passages": [...] }'
            className="mb-3 w-full rounded border border-neutral-300 px-3 py-2 font-mono text-xs leading-relaxed"
          />

          {errors.length > 0 && (
            <div className="mb-4 rounded border border-rose-200 bg-rose-50 px-3 py-2.5 text-xs text-rose-700">
              <p className="mb-1 font-semibold">This JSON doesn't match the expected structure:</p>
              <ul className="list-disc space-y-0.5 pl-4">
                {errors.map((e, i) => (
                  <li key={i}>{e}</li>
                ))}
              </ul>
            </div>
          )}

          <button
            onClick={handleParse}
            disabled={!jsonText.trim()}
            className="mb-6 rounded bg-rose-600 px-4 py-2 text-sm font-medium text-white hover:bg-rose-700 disabled:opacity-50"
          >
            Parse &amp; Preview
          </button>

          <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-4">
            <div className="mb-2 flex items-center justify-between">
              <h3 className="text-sm font-semibold text-neutral-800">Master AI Prompt</h3>
              <button
                onClick={handleCopyPrompt}
                className="rounded border border-neutral-300 bg-white px-2.5 py-1 text-xs font-medium text-neutral-600 hover:bg-neutral-100"
              >
                {copied ? 'Copied!' : 'Copy prompt'}
              </button>
            </div>
            <p className="mb-2 text-xs text-neutral-500">
              Paste this into ChatGPT, Claude, or similar (optionally with your own passage text) to get JSON back in
              the exact format this importer expects.
            </p>
            <pre className="max-h-64 overflow-y-auto whitespace-pre-wrap rounded border border-neutral-200 bg-white p-3 text-[11px] leading-relaxed text-neutral-700">
              {MASTER_AI_PROMPT}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ReadingTestWizard({ apiBase, onBack, initialTest, onSaved, backLabel = 'Back to Test Builder' }) {
  const isEditMode = Boolean(initialTest?._id);
  const [step, setStep] = useState(1);
  const [showImportModal, setShowImportModal] = useState(false);

  const [testTitle, setTestTitle] = useState(() => initialTest?.title || '');
  const [durationMinutes, setDurationMinutes] = useState(() => initialTest?.durationMinutes || 60);
  const [parts, setParts] = useState(() => (initialTest?.parts?.length ? initialTest.parts : [emptyPart(1), emptyPart(2), emptyPart(3)]));

  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState(null);
  const [savedTest, setSavedTest] = useState(null);
  const [isPublishing, setIsPublishing] = useState(false);
  const [isPublished, setIsPublished] = useState(() => Boolean(initialTest?.isPublished));

  function updatePart(partIndex, updatedPart) {
    setParts((prev) => prev.map((p, i) => (i === partIndex ? updatedPart : p)));
  }

  function handlePassageCountChange(value) {
    setParts((prev) => resizePartsCount(prev, value));
  }

  function addPassage() {
    setParts((prev) => (prev.length >= MAX_PASSAGES ? prev : [...prev, emptyPart(prev.length + 1)]));
  }

  function removePassage(i) {
    setParts((prev) =>
      prev.length <= 1 ? prev : prev.filter((_, idx) => idx !== i).map((p, idx) => ({ ...p, partNumber: idx + 1 }))
    );
  }

  function handleImportJson(parsedData) {
    if (parsedData.title) setTestTitle(parsedData.title);
    if (parsedData.durationMinutes) setDurationMinutes(parsedData.durationMinutes);
    setParts(mapImportJsonToParts(parsedData));
    setShowImportModal(false);
    setStep(2); // land teachers on the passage/question review right after import
  }

  const step1Valid = testTitle.trim().length > 0;
  const step2Valid = parts.length > 0 && parts.every((p) => p.passageText && p.passageText.trim().length > 0);

  function goNext() {
    setStep((s) => Math.min(3, s + 1));
  }
  function goBack() {
    setStep((s) => Math.max(1, s - 1));
  }

  function buildPayload() {
    return {
      title: testTitle.trim(),
      module: 'reading',
      durationMinutes: Number(durationMinutes) || 60,
      totalQuestions: countQuestions(parts),
      parts,
    };
  }

  async function handleSave() {
    setIsSaving(true);
    setSaveError(null);
    try {
      const payload = buildPayload();
      const url = isEditMode ? `${apiBase}/tests/${initialTest._id}` : `${apiBase}/tests`;
      const method = isEditMode ? 'PATCH' : 'POST';

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json', ...authHeaders() },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to save test.');

      setSavedTest(data.test);
      setIsPublished(Boolean(data.test.isPublished));
      if (onSaved) onSaved(data.test);
    } catch (err) {
      setSaveError(err.message);
    } finally {
      setIsSaving(false);
    }
  }

  async function handlePublish() {
    setIsPublishing(true);
    try {
      const res = await fetch(`${apiBase}/tests/${savedTest._id}/publish`, { method: 'POST', headers: authHeaders() });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed to publish test.');
      setSavedTest(data.test);
      setIsPublished(true);
      if (onSaved) onSaved(data.test);
    } catch (err) {
      alert(err.message);
    } finally {
      setIsPublishing(false);
    }
  }

  return (
    <div className="flex h-full flex-col bg-white">
      {/* Fixed header — "Import via JSON" lives here (not in the scrollable
          content) so it's reachable from any step. */}
      <div className="flex shrink-0 items-center justify-between border-b border-neutral-200 px-6 py-4">
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 text-sm font-medium text-neutral-500 transition hover:text-neutral-800"
        >
          ← {backLabel}
        </button>
        <button
          onClick={() => setShowImportModal(true)}
          className="flex items-center gap-1.5 rounded-lg border border-neutral-300 bg-white px-3 py-1.5 text-sm font-medium text-neutral-700 transition hover:bg-neutral-50"
        >
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4">
            <path d="M12 3v12m0 0 4-4m-4 4-4-4" />
            <path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2" />
          </svg>
          Import via JSON
        </button>
      </div>

      {/* Scrollable content — footer nav below is a real flex-shrink-0 bar,
          not `sticky`, so it always stays visible. */}
      <div className="flex-1 overflow-y-auto">
        <div className="mx-auto max-w-3xl px-6 pt-6 pb-10">
          <h1 className="mb-1 text-xl font-semibold">{isEditMode ? 'Edit Reading Test' : 'Create Reading Test'}</h1>
          <p className="mb-6 text-sm text-neutral-500">
            {isEditMode
              ? 'Update the passages and questions below, then save your changes.'
              : 'Build a reading test step by step, or paste AI-generated JSON to auto-populate it.'}
          </p>

          {/* Progress steps */}
          <div className="mb-8 flex items-center gap-2">
            {STEPS.map((label, i) => {
              const n = i + 1;
              const isActive = step === n;
              const isDone = step > n;
              return (
                <div key={label} className="flex flex-1 items-center gap-2">
                  <div
                    className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-xs font-semibold ${
                      isActive
                        ? 'bg-rose-600 text-white'
                        : isDone
                        ? 'bg-rose-100 text-rose-600'
                        : 'bg-neutral-100 text-neutral-400'
                    }`}
                  >
                    {isDone ? '✓' : n}
                  </div>
                  <span className={`hidden text-xs font-medium sm:inline ${isActive ? 'text-neutral-800' : 'text-neutral-400'}`}>
                    {label}
                  </span>
                  {n < STEPS.length && <div className={`h-px flex-1 ${isDone ? 'bg-rose-200' : 'bg-neutral-200'}`} />}
                </div>
              );
            })}
          </div>

          {/* Step 1 — Test Details */}
          {step === 1 && (
            <div className="rounded-lg border border-neutral-200 p-5">
              <label className="mb-1 block text-xs font-medium text-neutral-500">Test title</label>
              <input
                type="text"
                value={testTitle}
                onChange={(e) => setTestTitle(e.target.value)}
                placeholder="e.g. Cambridge 21 Test 4 — Academic Reading"
                className="mb-4 w-full rounded border border-neutral-300 px-3 py-2 text-sm"
              />

              <div className="flex gap-4">
                <div className="w-32">
                  <label className="mb-1 block text-xs font-medium text-neutral-500">Duration (min)</label>
                  <input
                    type="number"
                    value={durationMinutes}
                    onChange={(e) => setDurationMinutes(e.target.value)}
                    className="w-full rounded border border-neutral-300 px-3 py-2 text-sm"
                  />
                </div>
                <div className="w-40">
                  <label className="mb-1 block text-xs font-medium text-neutral-500">Number of passages</label>
                  <input
                    type="number"
                    min={1}
                    max={MAX_PASSAGES}
                    value={parts.length}
                    onChange={(e) => handlePassageCountChange(e.target.value)}
                    className="w-full rounded border border-neutral-300 px-3 py-2 text-sm"
                  />
                </div>
              </div>

              <p className="mt-4 text-xs text-neutral-500">
                Fill in passages and questions manually on the next step, or use{' '}
                <button onClick={() => setShowImportModal(true)} className="font-medium text-rose-600 underline underline-offset-2">
                  Import via JSON
                </button>{' '}
                (top right) to auto-populate everything from AI-generated content.
              </p>
            </div>
          )}

          {/* Step 2 — Passages & Questions */}
          {step === 2 && (
            <div>
              {parts.map((part, i) => (
                <div key={i} className="mb-4">
                  <div className="mb-1 flex items-center justify-between">
                    <span className="text-xs font-semibold uppercase tracking-wide text-neutral-400">
                      Passage {i + 1}
                    </span>
                    {parts.length > 1 && (
                      <button
                        onClick={() => removePassage(i)}
                        className="rounded border border-neutral-300 bg-white px-2.5 py-1 text-xs font-medium text-neutral-500 hover:bg-neutral-100"
                      >
                        Remove passage
                      </button>
                    )}
                  </div>
                  <PartEditor part={part} onChange={(updated) => updatePart(i, updated)} apiBase={apiBase} />
                </div>
              ))}

              <button
                onClick={addPassage}
                disabled={parts.length >= MAX_PASSAGES}
                className="rounded border border-dashed border-neutral-300 px-3 py-2 text-sm font-medium text-neutral-600 hover:bg-neutral-50 disabled:opacity-40"
              >
                + Add passage
              </button>
            </div>
          )}

          {/* Step 3 — Review & Save */}
          {step === 3 && (
            <div className="rounded-lg border border-neutral-200 p-5">
              {!savedTest ? (
                <>
                  <h2 className="mb-4 text-sm font-semibold text-neutral-800">Review before saving</h2>

                  <div className="mb-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-neutral-400">Title</p>
                    <p className="text-sm text-neutral-800">{testTitle || '—'}</p>
                  </div>

                  <div className="mb-2">
                    <p className="text-xs font-medium uppercase tracking-wide text-neutral-400">
                      {parts.length} passage{parts.length === 1 ? '' : 's'} · {countQuestions(parts)} question
                      {countQuestions(parts) === 1 ? '' : 's'}
                    </p>
                    <ul className="mt-1 space-y-1 text-sm text-neutral-700">
                      {parts.map((p, i) => (
                        <li key={i}>
                          <span className="font-medium">{p.title || `Passage ${i + 1}`}</span>
                          {' — '}
                          {(p.questionGroups || []).reduce((s, g) => s + (g.questions || []).length, 0)} question
                          {(p.questionGroups || []).reduce((s, g) => s + (g.questions || []).length, 0) === 1 ? '' : 's'}
                        </li>
                      ))}
                    </ul>
                  </div>

                  {saveError && <p className="mt-3 text-sm text-rose-600">{saveError}</p>}
                </>
              ) : (
                <>
                  <div className="mb-4 rounded border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">
                    ✅ "{savedTest.title}" {isEditMode ? 'updated' : 'saved as a draft'}.
                    {isPublished && ' It is now published and visible to students.'}
                  </div>
                  {!isPublished && (
                    <p className="text-sm text-neutral-500">
                      It's saved but not visible to students yet — hit "Publish Test" when you're ready to go live.
                    </p>
                  )}
                </>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Footer nav — fixed height bar, not sticky, so it always stays
          visible regardless of scroll position or ancestor overflow. */}
      <div className="shrink-0 border-t border-neutral-200 bg-white px-6 py-4">
        <div className="mx-auto flex max-w-3xl justify-between gap-3">
          <button
            onClick={goBack}
            disabled={step === 1}
            className="rounded border border-neutral-300 px-4 py-2 text-sm font-medium hover:bg-neutral-50 disabled:opacity-40"
          >
            Previous
          </button>

          {step < 3 && (
            <button
              onClick={goNext}
              disabled={(step === 1 && !step1Valid) || (step === 2 && !step2Valid)}
              className="rounded bg-rose-600 px-4 py-2 text-sm font-medium text-white hover:bg-rose-700 disabled:opacity-50"
            >
              Next
            </button>
          )}

          {step === 3 && !savedTest && (
            <button
              onClick={handleSave}
              disabled={isSaving || !step1Valid || !step2Valid}
              className="rounded bg-rose-600 px-4 py-2 text-sm font-medium text-white hover:bg-rose-700 disabled:opacity-50"
            >
              {isSaving ? 'Saving…' : isEditMode ? 'Save Changes' : 'Save Reading Test'}
            </button>
          )}

          {step === 3 && savedTest && !isPublished && (
            <button
              onClick={handlePublish}
              disabled={isPublishing}
              className="rounded bg-rose-600 px-4 py-2 text-sm font-medium text-white hover:bg-rose-700 disabled:opacity-50"
            >
              {isPublishing ? 'Publishing…' : 'Publish Test'}
            </button>
          )}

          {step === 3 && isPublished && (
            <button
              onClick={onBack}
              className="rounded bg-neutral-800 px-4 py-2 text-sm font-medium text-white hover:bg-neutral-900"
            >
              {backLabel}
            </button>
          )}
        </div>
      </div>

      {showImportModal && <ImportJsonModal onClose={() => setShowImportModal(false)} onImport={handleImportJson} />}
    </div>
  );
}
